version: 2.1
orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

commands:
  install_dependencies:
    steps:
      - run:
          name: Installing dependencies
          command: |
            cd app
            yarn install

  linter:
    steps:
      - run:
          name: Linter
          command: |
            cd app
            yarn lint
  builder:
    steps:
      - run:
          name: Build Docker Image
          command: |
            cd app
            docker build -t app .
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

  notify_slack_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

jobs:
  lint:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - install_dependencies
      - linter
      - notify_slack_fail
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - builder
      - notify_slack_pass
      - notify_slack_fail

workflows:
  build:
    jobs:
      - lint
      - build:
          requires:
            - lint
