name: API CI Workflow

on:
  push:
    branches:
      - "*"
    paths:
      - "api/src/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "api/src/**"

jobs:
  building-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Eclipse Temurin Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/ .ivy2/cache
            ~/ .sbt
            ~/ .m2
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run ScalaStyle
        working-directory: ./api
        run: sbt scalafmtCheckAll

      - name: Run Muti Test
        working-directory: ./api
        run: sbt test

      - name: Build the Docker image
        working-directory: ./api
        run: docker build -t api .

  slack-notify:
    runs-on: ubuntu-latest
    needs: building-stage
    steps:
      - name: Send Slack Notification Successful
        uses: rtCamp/action-slack-notify@v2
        if: ${{ needs.building-stage.result == 'success' }}
        env:
          SLACK_USERNAME: API CI Github Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Successfully🎉
          SLACK_COLOR: good
          SLACK_MESSAGE: CI Completion! Good job.
      - name: Send Slack Notification failureful
        uses: rtCamp/action-slack-notify@v2
        if: ${{ needs.building-stage.result == 'failure' }}
        env:
          SLACK_USERNAME: API CI Github Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Failurefully⚠️
          SLACK_COLOR: danger
          SLACK_MESSAGE: CI Failed! Please confirm.
