name: Slack Notification

on:
  workflow_call:
    inputs:
      f-slack-title:
        required: false
        type: string
        default: Failurefully⚠️
      f-slack-message:
        required: true
        type: string
      s-slack-title:
        required: false
        type: string
        default: Successfully🎉
      s-slack-message:
        required: true
        type: string
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification Successful
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_TITLE: ${{ inputs.s-slack-title }}
          SLACK_COLOR: good
          SLACK_MESSAGE: ${{ inputs.s-slack-message }}
      - name: Send Slack Notification failureful
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_USERNAME: CI Github Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: ${{ inputs.f-slack-title }}
          SLACK_COLOR: danger
          SLACK_MESSAGE: ${{ inputs.f-slack-message }}
