name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      job-name:
        required: true
        type: string
      github-run-id:
        required: true
        type: string
      slack-channel:
        required: true
        type: string
      webhook-url:
        required: true
        type: string

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: ${{ inputs.slack-channel }}
          slack-message: "Job ${{ inputs.job-name }} completed with status ${{ inputs.status }}. Run ID: ${{ inputs.github-run-id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
